"""
terminology.py
────────────────────────────────────────────────────────────────────────────
ChemoFilter · Scientific Terminology & Humanization Layer
• Global TERMINOLOGY_MAP with full expanded + abbreviated forms
• Tooltip definitions for every scientific term
• Human-readable label helpers for UI display
• NO logic changes — display layer only
────────────────────────────────────────────────────────────────────────────
"""

# ═════════════════════════════════════════════════════════════════════════════
# MASTER TERMINOLOGY MAP
# key  = internal variable name (lowercase)
# value = (display_label, tooltip_text)
# ═════════════════════════════════════════════════════════════════════════════

TERM = {
    # ── Physicochemical ───────────────────────────────────────────────────
    "mw":           ("Molecular Weight (MW)",
                     "Total mass of the molecule in Daltons (Da). Lipinski limit: ≤500 Da."),
    "logp":         ("Lipophilicity (LogP)",
                     "Octanol-water partition coefficient. Measures how soluble a compound is in fat vs water. Ideal drug range: -0.4 to 5.6."),
    "tpsa":         ("Topological Polar Surface Area (TPSA)",
                     "Sum of surface area of polar atoms (O, N). Predicts oral absorption and blood-brain barrier penetration. Ideal: ≤140 Ų for oral drugs."),
    "hbd":          ("Hydrogen Bond Donors (HBD)",
                     "Number of N–H and O–H groups that can donate a hydrogen bond. Lipinski limit: ≤5."),
    "hba":          ("Hydrogen Bond Acceptors (HBA)",
                     "Number of N and O atoms that can accept a hydrogen bond. Lipinski limit: ≤10."),
    "qed":          ("Drug-Likeness Score (QED)",
                     "Quantitative Estimate of Drug-likeness (0–1). Combines 8 molecular properties into a single score. QED > 0.6 is considered drug-like."),
    "sa_score":     ("Synthetic Accessibility Score (SA)",
                     "Estimates how easy a molecule is to synthesize (1=easy, 10=very hard). Based on fragment contributions and structural complexity."),
    "fsp3":         ("Fraction sp3 Carbons (Fsp3)",
                     "Proportion of saturated sp3-hybridized carbons. Higher values (>0.4) correlate with better aqueous solubility and clinical success."),
    "rotbonds":     ("Rotatable Bonds",
                     "Number of single bonds around which rotation is possible. High values (>10) reduce oral bioavailability."),
    "rings":        ("Ring Count",
                     "Total number of ring systems. Related to molecular rigidity and scaffold complexity."),
    "aromatic_rings": ("Aromatic Ring Count",
                       "Number of aromatic (π-conjugated) ring systems. Contributes to lipophilicity and metabolic liability."),
    "heavy_atoms":  ("Heavy Atom Count",
                     "Total number of non-hydrogen atoms. Used to calculate ligand efficiency."),
    "bertz_ct":     ("Topological Complexity (Bertz CT)",
                     "Bertz complexity index — a graph-theoretic measure of molecular complexity."),

    # ── Drug-Likeness Rules ───────────────────────────────────────────────
    "lipinski":     ("Lipinski Rule of Five (Ro5)",
                     "Oral drug-likeness rule: MW≤500, LogP≤5, HBD≤5, HBA≤10. Violations predict poor oral absorption."),
    "veber":        ("Veber Oral Bioavailability Rule",
                     "TPSA≤140 Ų AND RotBonds≤10. Compounds passing both rules have higher oral bioavailability in rats."),
    "ghose":        ("Ghose Drug-Like Filter",
                     "Physicochemical range filter: MW 160–480, LogP -0.4 to 5.6, heavy atoms 20–70."),
    "egan":         ("Egan Passive Intestinal Absorption",
                     "Predicts passive intestinal absorption: TPSA≤131 and LogP≤5.88."),
    "muegge":       ("Muegge Drug-Like Filter",
                     "Broader drug-likeness filter: MW 200–600, LogP -2 to 5, TPSA≤150."),
    "leadlikeness": ("Lead-Likeness Score",
                     "Identifies fragment-like leads: MW 250–350, LogP≤3.5, RotBonds≤7. Useful for fragment-based drug discovery."),
    "ro3":          ("Rule of Three (Ro3)",
                     "Fragment-like compounds: MW≤300, LogP≤3, HBD≤3, HBA≤3. Used in fragment screening campaigns."),

    # ── ADMET ─────────────────────────────────────────────────────────────
    "hia":          ("Human Intestinal Absorption (HIA)",
                     "Predicts whether the compound will be absorbed through the human intestinal wall after oral dosing."),
    "bbb":          ("Blood-Brain Barrier Penetration (BBB)",
                     "Predicts whether the compound can cross the blood-brain barrier. Key for CNS drug candidates."),
    "herg":         ("hERG Cardiac Liability",
                     "Predicted affinity for the hERG potassium channel. HIGH risk indicates potential cardiac toxicity (QT prolongation)."),
    "pains":        ("Pan-Assay Interference Compounds (PAINS)",
                     "Structural alerts identifying compounds that frequently give false positives in biological assays due to non-specific interactions."),
    "ames":         ("Ames Mutagenicity Risk",
                     "Bacterial mutagenicity assay prediction. Indicates potential genotoxicity and DNA damage."),
    "loggs":        ("Aqueous Solubility (logS)",
                     "Predicted aqueous solubility. logS > -4 is generally considered acceptable for oral drugs."),
    "cns_mpo":      ("CNS Multiparameter Optimisation Score (CNS MPO)",
                     "Wager CNS MPO score (0–6). Higher scores predict better CNS drug-like properties for brain-penetrant compounds."),
    "cyp_hits":     ("CYP450 Enzyme Inhibition Risk",
                     "Number of cytochrome P450 enzymes predicted to be inhibited. High CYP inhibition causes drug-drug interactions."),
    "ppb":          ("Plasma Protein Binding (PPB)",
                     "Fraction of drug bound to blood plasma proteins. Very high binding (>99%) reduces free drug concentration."),
    "oral_bio":     ("Oral Bioavailability Score",
                     "Composite score predicting the fraction of an orally administered dose that reaches systemic circulation unchanged."),

    # ── Scoring ───────────────────────────────────────────────────────────
    "leadscore":    ("Lead Optimisation Score",
                     "Composite drug discovery score (0–100). Integrates drug-likeness, ADMET, toxicity, and synthetic accessibility into a single decision metric."),
    "oralbioscore": ("Oral Bioavailability Score",
                     "Predicted oral bioavailability percentage based on physicochemical and ADMET properties."),
    "np_score":     ("Natural Product Likeness Score (NP Score)",
                     "Quantifies structural resemblance to known natural products. High scores indicate natural product-like scaffold."),
    "chemoscore":   ("ChemoFilter Composite Score",
                     "Platform-specific composite scoring metric combining physicochemical, ADMET, and safety parameters."),
    "stress":       ("Molecular Stress Score",
                     "Composite pharmacological stress from toxicity, conformational complexity, and chemical instability."),
    "promiscuity":  ("Promiscuity Risk Score",
                     "Predicts likelihood of non-selective binding to multiple off-targets. High scores increase toxicity risk."),
    "complexity":   ("Structural Complexity Index",
                     "Graph-theoretic complexity of the molecular framework. High complexity often reduces synthetic accessibility."),

    # ── Efficiency ────────────────────────────────────────────────────────
    "ligand_efficiency": ("Ligand Efficiency (LE)",
                          "Binding energy contribution per heavy atom (kcal/mol/HA). Guides scaffold optimisation toward smaller, potent molecules."),
    "lle":          ("Lipophilic Ligand Efficiency (LLE)",
                     "pIC50 minus LogP. Measures potency contribution independent of lipophilicity. LLE > 5 is excellent."),
    "ble":          ("Binding Efficiency Index (BEI)",
                     "Potency (pIC50 × 1000) divided by molecular weight. Normalises potency for molecular size."),

    # ── Comparison / Delta ────────────────────────────────────────────────
    "delta":        ("Difference (Δ)",
                     "Absolute difference in property value between test compound and reference compound."),
    "delta_mw":     ("Molecular Weight Difference (ΔMW)",
                     "Change in molecular weight vs reference. Negative = smaller, positive = larger."),
    "delta_logp":   ("Lipophilicity Difference (ΔLogP)",
                     "Change in LogP vs reference. Negative = more hydrophilic, positive = more lipophilic."),
    "delta_tpsa":   ("Polar Surface Area Difference (ΔTPSA)",
                     "Change in TPSA vs reference. Negative = less polar, positive = more polar."),
    "delta_qed":    ("Drug-Likeness Difference (ΔQED)",
                     "Change in QED score vs reference. Positive = improved drug-likeness."),
    "delta_sa":     ("Synthetic Difficulty Difference (ΔSA)",
                     "Change in synthetic accessibility score. Negative = easier to synthesise."),
    "delta_lead":   ("Lead Score Difference (ΔLead Score)",
                     "Change in composite Lead Optimisation Score. Positive = better overall profile."),

    # ── Quantum / Graph ───────────────────────────────────────────────────
    "homo_lumo":    ("HOMO-LUMO Gap Proxy",
                     "Approximation of the frontier molecular orbital energy gap. Wider gap = greater chemical stability and lower reactivity."),
    "electrophilicity": ("Electrophilicity Index (ω)",
                         "Measure of the molecule's tendency to accept electrons. High values indicate electrophilic character and potential reactivity."),
    "nucleophilicity": ("Nucleophilicity Index",
                        "Measure of electron-donating tendency. High values indicate nucleophilic reactivity."),
    "graph_entropy": ("Molecular Graph Entropy",
                      "Shannon entropy of the molecular graph degree distribution. Measures structural information content and complexity."),
    "wiener":       ("Wiener Topological Index",
                     "Sum of all shortest path lengths in the molecular graph. Related to boiling point and molecular branching."),
    "balaban":      ("Balaban Connectivity Index (J)",
                     "Graph-theoretic index highly sensitive to molecular branching. Used to distinguish structural isomers."),
    "connectivity": ("Molecular Connectivity Index (χ)",
                     "Randić connectivity index — quantifies molecular branching and predicts physical properties."),

    # ── Biological ────────────────────────────────────────────────────────
    "protein_binding": ("Protein–Ligand Binding Likelihood",
                        "Estimated probability of productive binding to a protein target based on physicochemical profile."),
    "pi_stacking":  ("π–π Stacking Potential",
                     "Likelihood of aromatic ring stacking interactions with protein aromatic residues (e.g., Phe, Tyr, Trp)."),
    "membrane_interaction": ("Membrane Interaction Likelihood",
                              "Probability of compound interaction with phospholipid bilayers. High values may indicate membrane accumulation or toxicity."),
    "cyp3a4":       ("CYP3A4 Metabolic Liability",
                     "Predicted susceptibility to metabolism by CYP3A4, the most abundant drug-metabolising enzyme (~50% of drugs)."),
    "cyp2d6":       ("CYP2D6 Metabolic Liability",
                     "Predicted susceptibility to CYP2D6 metabolism. Genetic polymorphisms create variability in drug response."),

    # ── Safety ────────────────────────────────────────────────────────────
    "cardiotox":    ("Cardiotoxicity Risk Indicator",
                     "Composite prediction of cardiac toxicity risk, primarily driven by hERG channel inhibition and lipophilicity."),
    "hepatotox":    ("Hepatotoxicity Risk Indicator",
                     "Predicted liver toxicity risk. High LogP and metabolic reactivity are key risk factors."),
    "genotox":      ("Genotoxicity Risk Indicator",
                     "Predicted DNA damage or mutagenicity risk. Structural alerts (nitro groups, intercalators) contribute to this score."),
    "overall_tox":  ("Overall Toxicity Index",
                     "Composite safety score integrating cardiotoxic, hepatotoxic, mutagenic, and reactive group signals."),
    "safety_margin": ("Safety Margin Proxy",
                      "Estimated ratio between therapeutic and toxic exposures. Higher values indicate a wider therapeutic window."),

    # ── Decision ─────────────────────────────────────────────────────────
    "go_no_go":     ("Go / No-Go Decision Indicator",
                     "Binary or tiered recommendation based on multi-parameter scoring. ✅ GO = advance to next stage; 🔴 NO-GO = requires redesign."),
    "rec_tier":     ("Development Recommendation Tier",
                     "Categorical recommendation: Strong Yes → advance; Conditional → address liabilities; Reject → structural redesign needed."),
    "tradeoff":     ("Multi-Parameter Tradeoff Score",
                     "Balance of improvements vs regressions across ADMET, efficiency, and safety dimensions."),
    "upgrade_pot":  ("Optimisation Potential Score",
                     "Estimated headroom for further molecular optimisation based on current property profile."),
}


def label(key: str) -> str:
    """Return the human-readable display label for a terminology key."""
    k = key.lower().replace(" ", "_").replace("-", "_")
    entry = TERM.get(k)
    if entry:
        return entry[0]
    # Fallback: capitalise and return
    return key.replace("_", " ").title()


def tip(key: str) -> str | None:
    """Return the tooltip/help text for a terminology key, or None."""
    k = key.lower().replace(" ", "_").replace("-", "_")
    entry = TERM.get(k)
    return entry[1] if entry else None


def label_tip(key: str) -> tuple:
    """Return (label, tooltip) tuple for use in st.metric / st.column."""
    return label(key), tip(key)


# ── Comparison mode display mapping ─────────────────────────────────────
# Maps internal _COMPARE_PROPS keys → human labels for table headers
COMPARE_LABELS = {
    "MW":          ("Molecular Weight (MW)",          "Da",  "mw"),
    "LogP":        ("Lipophilicity (LogP)",            "",    "logp"),
    "tPSA":        ("Polar Surface Area (TPSA)",       "Ų",  "tpsa"),
    "QED":         ("Drug-Likeness Score (QED)",       "",    "qed"),
    "SA_Score":    ("Synthetic Accessibility (SA)",    "",    "sa_score"),
    "LeadScore":   ("Lead Optimisation Score",         "",    "leadscore"),
    "OralBioScore":("Oral Bioavailability Score",      "%",   "oral_bio"),
    "HBD":         ("Hydrogen Bond Donors (HBD)",      "",    "hbd"),
    "HBA":         ("Hydrogen Bond Acceptors (HBA)",   "",    "hba"),
    "RotBonds":    ("Rotatable Bonds",                 "",    "rotbonds"),
    "NP_Score":    ("Natural Product Likeness",        "",    "np_score"),
    "ChemoScore":  ("ChemoFilter Composite Score",     "",    "chemoscore"),
}


def compare_label(prop_key: str) -> str:
    """Human-readable label for a comparison table column."""
    entry = COMPARE_LABELS.get(prop_key)
    return entry[0] if entry else label(prop_key)


def compare_tip(prop_key: str) -> str | None:
    """Tooltip for a comparison table column."""
    entry = COMPARE_LABELS.get(prop_key)
    if entry:
        return tip(entry[2])
    return tip(prop_key.lower())


# ── Radar chart category labels ──────────────────────────────────────────
RADAR_LABELS = {
    "QED×100":    "Drug-Likeness × 100 (QED)",
    "LeadScore":  "Lead Optimisation Score",
    "OralBioScore": "Oral Bioavailability Score",
    "BBB(%)":     "Blood-Brain Barrier Penetration (%)",
    "HIA(%)":     "Human Intestinal Absorption (%)",
}


def radar_label(key: str) -> str:
    return RADAR_LABELS.get(key, key)


# ── Section title map ────────────────────────────────────────────────────
SECTION_TITLES = {
    "overview":          "⬡ Compound Overview & Screening Summary",
    "filtering_lab":     "🧪 Architectural Filtering Laboratory",
    "dataset_intel":     "📊 Dataset Intelligence & Population Analytics",
    "diagnostics":       "🔬 Compound Diagnostics & Property Profiling",
    "3d_conformer":      "⬡ 3D Conformer Explorer (MMFF94-Optimised)",
    "metabolic_pulse":   "⬡ Metabolic Liability & Biotransformation Pulse",
    "boiled_egg":        "⬡ BOILED-EGG Absorption & Permeability Map",
    "analysis_suite":    "⬡ Analysis Suite — Similarity, PCA & Parallel Coordinates",
    "qsar_fragments":    "⬡ QSAR Regression & Fragment Decomposition",
    "comparison_mode":   "⚖️ Multi-Compound Comparative Intelligence",
    "scaffold_hopper":   "🔀 Scaffold Hopping & Bioisostere Discovery",
    "drug_class":        "💊 Drug Class Prediction & Target Category",
    "reaction_sim":      "⚗️ Medicinal Chemistry Reaction Simulator",
    "admet_bench":       "📐 ADMET Benchmarking vs Approved Drug Space",
    "ai_explainer":      "🤖 AI-Powered Scientific Explanation Engine",
    "external_data":     "🔬 External Scientific Data Enrichment",
}


def section_title(key: str) -> str:
    return SECTION_TITLES.get(key, key.replace("_", " ").title())


# ── Advanced feature humanisation map ───────────────────────────────────
# Used in comparison_mode and hyper system tabs
FEATURE_LABELS = {
    # Physicochemical expansion
    "polar_surface_dist_idx":      ("Polar Surface Distribution Index",
                                    "TPSA distributed per heavy atom — measures polarity concentration."),
    "hydrophobic_surface_ratio":   ("Hydrophobic Surface Ratio",
                                    "Fraction of molecular surface that is non-polar. Drives membrane permeability."),
    "mol_flexibility_idx":         ("Molecular Flexibility Index",
                                    "Rotatable bonds normalised by heavy atom count. High values reduce oral bioavailability."),
    "topo_complexity_score":       ("Topological Complexity Score",
                                    "Log-normalised Bertz complexity index. Reflects synthetic difficulty."),
    "shape_index":                 ("Molecular Shape Index (MW/Ring)",
                                    "MW divided by ring count — high values indicate linear/elongated scaffolds."),
    "atom_type_diversity":         ("Atomic Element Diversity",
                                    "Count of unique atomic elements. Higher diversity can improve selectivity."),
    "functional_group_density":    ("Functional Group Density",
                                    "Number of functional groups per heavy atom. High density increases reactivity."),
    "heteroatom_ratio":            ("Heteroatom Ratio",
                                    "Fraction of non-carbon heavy atoms. Higher ratios increase polarity and H-bonding potential."),
    "aromaticity_score":           ("Aromaticity Score",
                                    "Fraction of aromatic heavy atoms. Drives lipophilicity and metabolic liability."),
    "ring_strain_proxy":           ("Ring Strain Indicator",
                                    "Count of strained 3- and 4-membered rings. High strain increases chemical instability."),
    "hb_network_density":          ("Hydrogen Bond Network Density",
                                    "Total H-bond donors+acceptors per heavy atom. Predicts solubility and permeability balance."),
    "rotational_entropy_proxy":    ("Rotational Conformational Entropy",
                                    "Rotatable bonds per heavy atom. Reflects conformational flexibility."),
    "mol_symmetry_score":          ("Molecular Symmetry Score",
                                    "Token-based symmetry estimate from canonical SMILES. Higher symmetry = simpler synthesis."),
    "fragment_diversity_score":    ("Ring System Diversity Score",
                                    "Fraction of unique ring systems. Measures scaffold novelty."),
    "saturation_index":            ("Carbon Saturation Index (Fsp3)",
                                    "Fraction of sp3-hybridised carbons. Higher values correlate with better solubility and clinical success rates."),
    "carbon_hybridization_ratio":  ("sp3 Carbon Fraction",
                                    "Ratio of tetrahedral carbons to total carbons. Fsp3 > 0.3 is associated with oral drug success."),
    "bond_type_diversity":         ("Bond Type Diversity",
                                    "Count of distinct bond types (single, double, aromatic). Reflects chemical richness."),
    "partial_charge_spread_proxy": ("Charge Distribution Spread Proxy",
                                    "Approximation of electrostatic charge variation across the molecule."),
    "electronic_density_proxy":    ("Electronic Density Proxy",
                                    "TPSA/MW ratio × 100 — estimates polar electron density per unit mass."),
    "mw_per_ring":                 ("Molecular Weight per Ring System (Da)",
                                    "Average mass contributed by each ring system. High values indicate large, bulky scaffolds."),
    # Drug-likeness deep
    "ext_ro5_score":               ("Extended Rule of Five Compliance Score",
                                    "Fraction of Lipinski Ro5 criteria passed (0–1). Higher = more drug-like."),
    "ro3_compliance":              ("Rule of Three Compliance (Fragment-Like)",
                                    "1 if compound meets Ro3 criteria for fragment screening."),
    "lead_likeness_score":         ("Lead-Likeness Score",
                                    "1 if compound falls within the lead-like chemical space: MW 250–350, LogP ≤3.5, RotBonds ≤7."),
    "oral_bioavail_score":         ("Predicted Oral Bioavailability Score",
                                    "Composite score predicting fraction of oral dose reaching systemic circulation."),
    "cns_penetration_score":       ("CNS Penetration Likelihood Score",
                                    "Multi-parameter score predicting blood-brain barrier permeability for CNS drug candidates."),
    "efflux_risk_proxy":           ("Efflux Transporter Risk (P-gp) Proxy",
                                    "Predicted P-glycoprotein efflux liability. High efflux reduces CNS exposure and oral absorption."),
    "ppb_proxy":                   ("Plasma Protein Binding Proxy",
                                    "Estimated fraction bound to plasma proteins. Very high binding reduces free drug available for pharmacological action."),
    "distribution_index":          ("Volume of Distribution Index Proxy",
                                    "LogP/TPSA ratio — approximates tendency to distribute into tissues vs plasma."),
    "drug_efficiency_score":       ("Drug Efficiency Score (QED/SA)",
                                    "Ratio of drug-likeness to synthetic difficulty. High values indicate quality compounds that are easy to make."),
    "chem_beauty_score":           ("Chemical Beauty Score (QED × 100)",
                                    "QED expressed as 0–100 scale. Reflects overall aesthetic drug-likeness."),
    "developability_index":        ("Developability Index",
                                    "Composite of oral bioavailability, CNS penetration, and Ro5 compliance."),
    "optim_readiness_score":       ("Optimisation Readiness Score",
                                    "Weighted combination of synthetic accessibility and drug-likeness headroom."),
    "bcs_class_proxy":             ("Biopharmaceutics Classification System (BCS) Class Proxy",
                                    "Predicted BCS class (I–IV) based on solubility and permeability proxies."),
    "abad_score":                  ("Absorption & Distribution Score (ABAD)",
                                    "Binary absorption/distribution composite (0–1) based on TPSA and MW."),
    "gse_score":                   ("General Solubility Equation Score (GSE)",
                                    "Yalkowsky solubility estimate based on LogP and MW."),
    "pfizer_3_75_rule":            ("Pfizer Safety Rule (LogP<3, TPSA>75)",
                                    "1 if compound passes Pfizer's empirical safety filter: LogP<3 AND TPSA>75 Ų."),
    "gsk_4_400_rule":              ("GSK Safety Rule (LogP<4, MW<400)",
                                    "1 if compound passes GSK's permissiveness filter: LogP<4 AND MW<400 Da."),
    "mce18_score":                 ("Medicinal Chemistry Evolution Score (MCE-18)",
                                    "Combines Fsp3 and ring count to assess structural novelty in a medicinal chemistry context."),
    "natural_product_likeness":    ("Natural Product Likeness Score",
                                    "Structural resemblance to known natural products. Higher scores may improve selectivity."),
    "fda_similarity_score":        ("FDA-Approved Drug Similarity Score",
                                    "Normalised Lead Score as proxy for similarity to approved drugs."),
    # Risk / Tox
    "reactive_group_density":      ("Reactive Functional Group Density",
                                    "Count of chemically reactive substructures per heavy atom. High density increases non-specific toxicity."),
    "toxicophore_count":           ("Toxicophore Alert Count",
                                    "Number of structural fragments known to be associated with toxicity."),
    "lipophilicity_tox_risk":      ("Lipophilicity-Driven Toxicity Risk",
                                    "Estimated toxicity contribution from high lipophilicity. LogP > 3 escalates risk."),
    "aggregation_risk":            ("Molecular Aggregation Risk",
                                    "Tendency to self-aggregate in assay conditions — a major source of false-positive biological activity."),
    "pains_alert_count":           ("PAINS Structural Alert Count",
                                    "Number of Pan-Assay Interference (PAINS) patterns detected."),
    "struct_instability_idx":      ("Structural Chemical Instability Index",
                                    "Composite of high lipophilicity and low polarity that predicts chemical instability."),
    "oxidative_liability":         ("Oxidative Metabolic Liability",
                                    "Susceptibility to CYP-mediated oxidative metabolism, driven by aromatic ring content."),
    "metabolic_instability":       ("Metabolic Instability Score",
                                    "Estimated ease of enzymatic breakdown. High metabolic instability reduces compound half-life."),
    "bioaccumulation_risk":        ("Bioaccumulation Risk Index",
                                    "Predicted tendency to accumulate in biological tissues. LogP > 3 is a key driver."),
    "clearance_risk":              ("Hepatic Clearance Risk",
                                    "Predicted rate of metabolic clearance. High synthetic complexity increases unpredictable clearance."),
    "safety_margin_proxy":         ("Safety Margin Proxy",
                                    "Inverse of active toxicity flags. Higher = wider predicted therapeutic window."),
    "dose_escalation_risk":        ("Dose Escalation Risk",
                                    "Predicted difficulty in escalating dose due to toxicity liabilities."),
    "off_target_risk":             ("Off-Target Interaction Risk",
                                    "Predicted likelihood of binding to unintended biological targets. Driven by lipophilicity and MW."),
    "chem_reactivity_score":       ("Chemical Reactivity Score",
                                    "Estimated electrophilic or nucleophilic reactivity. High reactivity causes covalent off-target modification."),
    "genotoxicity_proxy":          ("Genotoxicity Risk Proxy",
                                    "Nitrogen-pattern-based estimate of mutagenic potential."),
    "cardiotoxicity_proxy":        ("Cardiotoxicity Risk Indicator",
                                    "Composite of hERG liability and lipophilicity — major driver of clinical drug attrition."),
    "hepatotoxicity_proxy":        ("Hepatotoxicity Risk Indicator",
                                    "Predicted liver toxicity based on LogP and chemical reactivity."),
    "reproductive_tox_proxy":      ("Reproductive Toxicity Risk Proxy",
                                    "Estimated reproductive/developmental toxicity from lipophilicity and molecular size."),
    "mutagenicity_proxy":          ("Mutagenicity Risk Proxy",
                                    "Predicted mutagenicity from structural features and known alerts."),
    "overall_tox_index":           ("Overall Toxicity Index",
                                    "Composite multi-organ toxicity prediction combining 10+ risk signals."),
    # Structure / Scaffold
    "scaffold_stability_score":    ("Scaffold Chemical Stability Score",
                                    "Aromatic ring fraction of scaffold — aromatic scaffolds are generally more metabolically stable."),
    "scaffold_novelty_score":      ("Scaffold Novelty Score",
                                    "Heteroatom diversity in ring systems — higher heteroatom types suggest novel scaffolds."),
    "scaffold_reusability_idx":    ("Scaffold Reusability Index",
                                    "Fraction of common pharmacophoric ring systems (benzene, pyridine, piperazine)."),
    "substituent_diversity":       ("Substituent Diversity",
                                    "Fraction of atoms outside ring systems — measures decorating group variety."),
    "branching_factor":            ("Molecular Branching Factor",
                                    "Fraction of atoms with degree > 2. High branching increases 3D character."),
    "mol_tree_depth":              ("Molecular Tree Depth",
                                    "Longest shortest path normalised by heavy atom count. Measures molecular elongation."),
    "core_rigidity_score":         ("Core Scaffold Rigidity Score",
                                    "Fraction of non-rotatable bonds. Higher rigidity reduces conformational entropy penalty on binding."),
    "fragment_reusability":        ("Pharmacophoric Fragment Reusability",
                                    "Fraction of common pharmacophoric patterns (OH, NH2, carbonyl, phenyl) present."),
    "struct_redundancy_score":     ("Structural Redundancy Score",
                                    "SMILES token repetition — higher values indicate repeating motifs."),
    "substructure_freq_score":     ("Drug-Fragment Frequency Score",
                                    "Prevalence of common drug-like substructural fragments."),
    "murcko_complexity":           ("Murcko Framework Complexity",
                                    "Complexity based on ring systems and substituent count."),
    "ring_system_diversity":       ("Ring System Diversity Index",
                                    "Fraction of unique ring sizes relative to total rings."),
    "linker_flexibility":          ("Inter-Ring Linker Flexibility",
                                    "Rotatable bonds between ring systems. Flexible linkers allow induced-fit binding but reduce oral absorption."),
    "terminal_group_count":        ("Terminal Functional Group Count",
                                    "Number of degree-1 heavy atoms. Terminal groups are primary sites for metabolic modification."),
    "heterocycle_richness":        ("Heterocyclic Ring Richness",
                                    "Fraction of ring systems containing heteroatoms. Rich heterocycles correlate with target selectivity."),
    # Metabolic deep
    "phase1_rxn_count":            ("Phase I Metabolic Reaction Count",
                                    "Predicted number of Phase I CYP-mediated reactions (oxidation, hydroxylation, etc.)."),
    "phase2_conjugation_likelihood": ("Phase II Conjugation Likelihood",
                                     "Predicted probability of glucuronidation or sulfation by Phase II enzymes."),
    "metabolic_hotspot_density":   ("Metabolic Hotspot Density",
                                    "Phase I reactions per unit molecular mass — high density indicates rapid metabolism."),
    "enzyme_interaction_likelihood": ("Metabolic Enzyme Interaction Likelihood",
                                      "Predicted probability of significant CYP enzyme interaction."),
    "clearance_speed_proxy":       ("Predicted Metabolic Clearance Speed",
                                    "Estimated hepatic clearance rate. High = rapid elimination; low = long half-life."),
    "metabolite_toxicity_risk":    ("Metabolite Toxicity Risk",
                                    "Predicted toxicity of metabolic products. High lipophilicity and slow clearance increase risk."),
    "stability_under_oxidation":   ("Oxidative Metabolic Stability",
                                    "Resistance to CYP-mediated oxidation. Low aromatic content = greater stability."),
    "hydrolysis_susceptibility":   ("Hydrolytic Stability (Ester/Amide)",
                                    "Susceptibility to hydrolysis of ester and amide bonds in biological media."),
    "biotransformation_complexity": ("Biotransformation Pathway Complexity",
                                     "Composite of Phase I and Phase II metabolic complexity."),
    "cyp3a4_risk":                 ("CYP3A4 Metabolic Liability",
                                    "Predicted susceptibility to the major drug-metabolising enzyme CYP3A4."),
    "cyp2d6_risk":                 ("CYP2D6 Metabolic Liability",
                                    "Predicted CYP2D6 interaction. Genetic polymorphisms cause highly variable patient responses."),
    "ugt_liability":               ("UGT Glucuronidation Liability",
                                    "Predicted UDP-glucuronosyltransferase substrate probability."),
    "aldehyde_oxidase_risk":       ("Aldehyde Oxidase (AO) Liability",
                                    "Predicted AO metabolism risk. AO metabolises nitrogen heterocycles."),
    "mao_liability":               ("Monoamine Oxidase (MAO) Liability",
                                    "Predicted MAO substrate potential. Important for CNS compounds with amine groups."),
    "gut_microbiome_risk":         ("Gut Microbiome Biotransformation Risk",
                                    "Predicted intestinal microbial degradation. Relevant for oral drugs."),
    # Graph theory
    "graph_diameter":              ("Molecular Graph Diameter",
                                    "Longest shortest path in the molecular graph — measures molecular elongation."),
    "avg_shortest_path":           ("Average Topological Path Length",
                                    "Mean shortest path between all atom pairs. Related to molecular compactness."),
    "node_centrality_variance":    ("Atom Centrality Variance",
                                    "Variance in degree centrality — high variance indicates hub atoms dominating connectivity."),
    "edge_density":                ("Bond Density",
                                    "Bonds relative to maximum possible — high density indicates compact polycyclic structures."),
    "clustering_coeff_proxy":      ("Local Clustering Coefficient Proxy",
                                    "Approximation of aromatic clustering — fraction of aromatic atoms."),
    "graph_entropy":               ("Molecular Graph Entropy",
                                    "Shannon entropy of degree distribution. High entropy = high structural information content."),
    "connectivity_index":          ("Molecular Connectivity Index (χ)",
                                    "Randić index summing 1/√(di×dj) over all bonds. Predicts physical properties."),
    "wiener_index_proxy":          ("Wiener Topological Index (Normalised)",
                                    "Normalised sum of all shortest path lengths. Related to molar volume and boiling point."),
    "balaban_index_proxy":         ("Balaban Connectivity Index (J)",
                                    "Highly discriminating graph index sensitive to molecular branching."),
    "graph_symmetry_score":        ("Molecular Graph Symmetry Score",
                                    "Inverse of unique degree count. High symmetry predicts simpler NMR and synthesis."),
    "cycle_distribution_score":    ("Ring Size Distribution Diversity",
                                    "Variety of ring sizes — diverse ring systems suggest complex scaffolds."),
    "bridge_bond_count":           ("Bridge Bond Count",
                                    "Single bonds not in rings whose removal would disconnect the graph. Vulnerable to metabolic cleavage."),
    "hub_atom_score":              ("Hub Atom Connectivity Score",
                                    "Maximum degree / average degree. High scores identify quaternary centres."),
    "subgraph_diversity":          ("Ring Subgraph Diversity",
                                    "Fraction of unique ring systems — measures scaffold diversity."),
    # Quantum
    "homo_lumo_gap_proxy":         ("HOMO–LUMO Energy Gap Proxy",
                                    "Approximation of frontier orbital energy gap. Wider gap = greater chemical stability."),
    "electrophilicity_idx":        ("Electrophilicity Index (ω)",
                                    "Tendency to accept electrons. High values indicate electrophilic warheads — watch for off-target covalent binding."),
    "nucleophilicity_idx":         ("Nucleophilicity Index",
                                    "Electron-donating tendency. Important for Michael acceptor and nucleophile interactions."),
    "hardness_proxy":              ("Chemical Hardness Proxy (η)",
                                    "Resistance to charge transfer. Hard molecules are more stable and less reactive."),
    "softness_proxy":              ("Chemical Softness Proxy (σ)",
                                    "Inverse of hardness. Soft molecules are more polarisable and reactive."),
    "polarizability_estimate":     ("Molecular Polarizability Estimate",
                                    "Estimate of electron cloud deformability. High polarizability improves π-stacking and hydrophobic interactions."),
    "ionization_potential_proxy":  ("Ionisation Potential Proxy",
                                    "Approximate energy to remove an electron. Related to oxidative metabolic stability."),
    "electron_affinity_proxy":     ("Electron Affinity Proxy",
                                    "Tendency to accept electrons. High affinity may predict electrophilic toxicity."),
    "charge_transfer_potential":   ("Charge Transfer Potential",
                                    "Estimated tendency for intramolecular or intermolecular charge transfer interactions."),
    # Interaction
    "protein_binding_likelihood":  ("Protein–Ligand Binding Likelihood",
                                    "Estimated probability of specific protein binding based on drug-like physicochemical profile."),
    "hydrophobic_interaction_score": ("Hydrophobic Interaction Score",
                                      "Lipophilicity-driven estimate of hydrophobic contact with protein binding pockets."),
    "hbond_potential_score":       ("Hydrogen Bond Potential Score",
                                    "Combined H-bond donor + acceptor capacity normalised by heavy atom count."),
    "pi_pi_stacking_potential":    ("π–π Aromatic Stacking Potential",
                                    "Predicted aromatic ring stacking with protein residues (Phe, Tyr, His, Trp)."),
    "ionic_interaction_likelihood": ("Ionic Interaction Likelihood",
                                     "Presence of formal charges predicting salt bridge or charge-charge interactions."),
    "surface_complementarity_score": ("Binding Site Surface Complementarity",
                                      "TPSA/MW ratio approximating polar complementarity with binding pocket."),
    "pocket_fit_proxy":            ("Target Binding Pocket Fit Proxy",
                                    "Multi-parameter estimate of how well the compound fits a typical drug-binding pocket."),
    # Evolutionary
    "optim_gradient_direction":    ("Optimisation Gradient Direction",
                                    "Headroom for drug-likeness improvement: 1 − QED. Larger values indicate more room to improve."),
    "structural_mutability_score": ("Structural Mutability Score",
                                    "Ease of structural modification: inverse of synthetic accessibility."),
    "scaffold_adaptability":       ("Scaffold Chemical Adaptability",
                                    "Flexibility and saturated carbon content — indicates tolerance to bioisosteric substitution."),
    "modification_sensitivity":    ("Property Sensitivity to Structural Change",
                                    "Proximity to property boundaries (MW, LogP). High sensitivity means small changes have large effects."),
    "feature_elasticity":          ("Property Profile Elasticity",
                                    "Drug-likeness × Lead Score contribution per unit of synthetic difficulty."),
    "optim_path_length_estimate":  ("Estimated Optimisation Steps to Target Profile",
                                    "Approximate number of structural modification cycles needed to reach ideal QED of 0.9."),
    "improvement_ceiling_estimate": ("Maximum Achievable Drug-Likeness Ceiling",
                                     "Estimated maximum QED attainable given current synthetic accessibility constraints."),
    # Tradeoffs
    "lipophilicity_vs_solubility": ("Lipophilicity vs Aqueous Solubility Balance",
                                    "Balance between membrane permeability (needs LogP) and aqueous solubility (needs low LogP). Ideal at LogP ~2.5."),
    "potency_vs_toxicity":         ("Potency vs Toxicity Risk Tradeoff",
                                    "Net benefit of predicted potency after penalisation for toxicity flags."),
    "stability_vs_flexibility":    ("Conformational Stability vs Flexibility Balance",
                                    "Balance between rigid scaffold (favours binding) and flexible molecule (favours absorption)."),
    "size_vs_efficiency":          ("Molecular Size vs Efficiency Tradeoff",
                                    "Ligand efficiency accounting for MW — favours smaller, potent molecules."),
    "permeability_vs_clearance":   ("Membrane Permeability vs Metabolic Clearance Balance",
                                    "Low TPSA (permeability) vs low LogP (clearance) balance — fundamental oral drug design tradeoff."),
    "multi_objective_score":       ("Multi-Objective Optimisation Score (MOO)",
                                    "Geometric mean of all five tradeoff scores. Compounds with high MOO are well-balanced across all dimensions."),
    # Synthesis
    "synthetic_step_estimate":     ("Estimated Synthetic Steps",
                                    "Approximate number of synthetic transformations needed. Based on SA Score."),
    "rxn_pathway_complexity":      ("Reaction Pathway Complexity Index",
                                    "Composite of SA score, ring count, and molecular weight."),
    "protecting_group_necessity":  ("Protecting Group Requirement",
                                    "Estimated need for protecting group strategies during synthesis."),
    "fg_compatibility_score":      ("Functional Group Synthetic Compatibility",
                                    "Fraction of reactive groups not requiring special handling. High = compatible chemistry."),
    "reaction_risk_score":         ("Synthetic Reaction Risk Score",
                                    "Probability of problematic reactions during multi-step synthesis."),
    "scale_up_feasibility":        ("Manufacturing Scale-Up Feasibility",
                                    "Predicted ease of scaling synthesis to kilogram scale for clinical supply."),
    "yield_uncertainty_proxy":     ("Synthetic Yield Uncertainty Proxy",
                                    "Expected variability in step yields based on complexity and reactive group content."),
    # Biology
    "membrane_interaction_likelihood": ("Phospholipid Membrane Interaction Likelihood",
                                        "Probability of compound association with biological membranes, which can cause phospholipidosis."),
    "enzyme_inhibition_potential": ("Enzyme Inhibition Potential",
                                    "Predicted potency for enzyme active site binding based on physicochemical profile."),
    "transporter_interaction_proxy": ("Drug Transporter Interaction Proxy",
                                      "P-gp and ABC transporter substrate likelihood based on MW and polarity."),
    "metabolic_pathway_diversity": ("Metabolic Pathway Diversity",
                                    "Number of distinct metabolic transformation pathways predicted."),
    "bioavailability_decay_score": ("Oral Bioavailability Decay Score",
                                    "Predicted rate of bioavailability loss due to metabolism and efflux."),
    "tissue_distribution_proxy":   ("Tissue Distribution Coefficient Proxy",
                                    "LogP-driven estimate of compound tendency to distribute into peripheral tissues."),
    # Micro chemistry
    "electron_cloud_proxy":        ("Electron Cloud Delocalisation Proxy",
                                    "π-electron fraction — measures extent of electron delocalisation across aromatic systems."),
    "local_polarity_variance":     ("Local Polarity Variance",
                                    "Variation in electrostatic environment across the molecule."),
    "bond_polarization_idx":       ("Bond Polarisation Index",
                                    "Fraction of polar (heteroatom-containing) bonds in the molecular graph."),
    "reactive_center_density":     ("Reactive Centre Density",
                                    "Charged or radical atoms per heavy atom — predicts non-specific reactivity."),
    "steric_hindrance_score":      ("Steric Hindrance Score",
                                    "Quaternary carbon density — indicates steric congestion around reaction centres."),
    "intramolecular_interaction":  ("Intramolecular H-Bond Potential",
                                    "Product of H-bond donors × acceptors normalised by heavy atoms — predicts intramolecular H-bond formation."),
    "hbond_geometry_score":        ("H-Bond Donor/Acceptor Geometry Score",
                                    "Ratio-based metric for optimal H-bond donor-to-acceptor balance."),
    "lone_pair_density":           ("Lone Pair Electron Density",
                                    "Proportion of oxygen and nitrogen atoms — high lone pair density drives H-bond acceptance."),
    "charge_separation_potential": ("Formal Charge Separation Potential",
                                    "Magnitude of formal charge distribution across the molecule."),
    "dipole_proxy":                ("Molecular Dipole Moment Proxy",
                                    "|LogP| × TPSA / MW — approximation of overall molecular polarity."),
    "pi_electron_score":           ("π-Electron Delocalisation Score",
                                    "Aromatic atom fraction — measures extent of conjugated π-electron systems."),
    "orbital_overlap_approx":      ("Orbital Overlap Approximation",
                                    "Fraction of conjugated atoms (aromatic + unsaturated). Predicts reactivity toward electrophiles."),
    "local_strain_score":          ("Local Ring Strain Score",
                                    "Normalised count of strained small rings relative to aromatic systems."),
    "substituent_electronic_effect": ("Substituent Electronic Effect Score",
                                      "Halogen density — quantifies electron-withdrawing substituent effects (inductive)."),
    "inductive_effect_strength":   ("Inductive Effect Strength",
                                    "Heteroatom substitution on sp3 carbons — measures σ-inductive electronic effects."),
    "resonance_stabilization":     ("Resonance Stabilisation Score",
                                    "Aromatic atom fraction of conjugated system — measures resonance delocalisation."),
    "charge_mobility":             ("Charge Mobility Index",
                                    "Product of orbital overlap and π-electron score — estimates charge transport ability."),
    # Meta / Engine
    "engine_agreement_score":      ("Predictive Model Agreement Score",
                                    "Fraction of consensus among all scoring engines. High agreement = high confidence prediction."),
    "prediction_stability_idx":    ("Prediction Stability Index",
                                    "Inverse coefficient of variation across engine scores. High = stable, reproducible predictions."),
    "confidence_interval_range":   ("Prediction Confidence Interval Width (95% CI)",
                                    "2× standard deviation of engine scores. Narrow CI = more precise prediction."),
    "engine_divergence_score":     ("Inter-Model Divergence Score",
                                    "Normalised standard deviation of engine outputs. Low divergence = high model consensus."),
    "consensus_strength":          ("Model Consensus Strength",
                                    "Fraction of models scoring within one standard deviation of the mean."),
    "reliability_score":           ("Overall Prediction Reliability Score",
                                    "Composite of agreement, stability, and consensus — measures how trustworthy the prediction is."),
    "engine_count":                ("Active Prediction Model Count",
                                    "Number of independent scoring models contributing to the consensus."),
    "top_engine_score":            ("Highest Individual Model Score",
                                    "Maximum score from any single model — upper bound of predicted activity."),
    "bottom_engine_score":         ("Lowest Individual Model Score",
                                    "Minimum score from any single model — lower bound of predicted activity."),
    "engine_spread_pct":           ("Model Score Range (% of Mean)",
                                    "Max–min spread as percentage of mean score. High spread indicates model disagreement."),
    # Efficiency deep
    "ligand_efficiency":           ("Ligand Efficiency (LE)",
                                    "kcal/mol per heavy atom proxy. The gold standard efficiency metric in fragment-based drug discovery."),
    "lipophilic_efficiency":       ("Lipophilic Ligand Efficiency (LLE)",
                                    "pIC50 – LogP. Optimising LLE drives potency gains independent of lipophilicity increases."),
    "property_efficiency_score":   ("Property Efficiency Score",
                                    "Composite physicochemical efficiency: QED contribution minus lipophilicity and polarity penalties."),
    "optim_cost_estimate":         ("Estimated Optimisation Cost",
                                    "Weighted SA and drug-likeness gap — proxy for medicinal chemistry effort required."),
    "synth_feasibility_score":     ("Synthetic Feasibility Score",
                                    "Inverse of SA Score normalised to 0–1. Higher = easier to synthesise."),
    "dev_cost_proxy":              ("Estimated Development Cost Proxy",
                                    "Composite of MW, SA, and rule violations — proxy for preclinical development effort."),
    "iteration_complexity":        ("Optimisation Iteration Complexity",
                                    "Estimated number of design-make-test cycles needed to reach acceptable drug candidate profile."),
    "lle_score":                   ("Lipophilic Ligand Efficiency (LLE)",
                                    "pIC50 minus LogP — measures potency contribution independent of lipophilicity."),
    "ble_score":                   ("Binding Efficiency Index (BEI)",
                                    "pIC50 × 1000 / MW — normalises potency for molecular weight."),
    "atse_score":                  ("Atom-Type Scaffold Efficiency (ATSE)",
                                    "QED divided by SA score fraction — combined quality and accessibility metric."),
    "group_efficiency":            ("Functional Group Efficiency",
                                    "Drug-likeness contribution per functional group — measures chemical efficiency of each pharmacophoric element."),
    "binding_efficiency_idx":      ("Binding Efficiency Index (BEI Variant)",
                                    "pIC50 proxy × 1000 / MW — size-normalised binding efficiency."),
    "kinetic_solubility_proxy":    ("Kinetic Aqueous Solubility Proxy",
                                    "TPSA / (|LogP| + 1) — approximates kinetic solubility in PBS buffer."),
    "permeability_efficiency":     ("Membrane Permeability Efficiency",
                                    "Fraction of non-polar surface area. Higher = greater passive permeability."),
    # Data science
    "z_score_mw":                  ("Molecular Weight Z-Score (vs Dataset)",
                                    "Standard deviations from mean MW of the current dataset. |Z| > 2 = outlier."),
    "z_score_logp":                ("Lipophilicity Z-Score (vs Dataset)",
                                    "Standard deviations from mean LogP of the current dataset."),
    "z_score_qed":                 ("Drug-Likeness Z-Score (vs Dataset)",
                                    "Standard deviations from mean QED of the current dataset."),
    "mahalanobis_proxy":           ("Mahalanobis Distance Proxy",
                                    "Multi-dimensional statistical distance from dataset centre. High values indicate outliers."),
    "outlier_classification_score": ("Statistical Outlier Classification Score",
                                     "1 if any property Z-score exceeds 2 — flags compounds far from dataset mean."),
    "feature_correlation_divergence": ("Property Correlation Divergence",
                                       "Deviation from expected LogP–MW correlation. High divergence indicates unusual physicochemical profile."),
    # Meta intelligence
    "confidence_weighted_score":   ("Confidence-Weighted Composite Score",
                                    "Mean engine score × model agreement confidence. Penalises uncertain predictions."),
    "risk_adjusted_score":         ("Toxicity Risk-Adjusted Lead Score",
                                    "Lead Score penalised by PAINS and hERG flags. Better reflects true development value."),
    "robustness_score":            ("Prediction Robustness Score",
                                    "Inverse coefficient of variation across engine scores. High robustness = reliable prediction."),
    "explainability_score":        ("Prediction Explainability Score",
                                    "Structural simplicity + drug-likeness — simpler, drug-like molecules have more interpretable predictions."),
    "decision_clarity_index":      ("Decision Clarity Index",
                                    "Absolute margin from the 50-point decision boundary. High clarity = unambiguous Go or No-Go."),
    "model_agreement_entropy":     ("Model Agreement Entropy",
                                    "Inverse normalised Shannon entropy of engine score distribution. High = uniform agreement."),
    # Benchmark
    "drug_space_distance":         ("Distance from Approved Drug Chemical Space",
                                    "100 − percentile rank. Higher = further from FDA approved drug property space."),
    "top_drug_similarity":         ("Approved Drug Physicochemical Similarity",
                                    "Percentile rank vs FDA approved drug property distributions (0–1 scale)."),
    "outlier_detection_score":     ("Property Profile Outlier Score",
                                    "Normalised standard deviation of percentile ranks. High = inconsistent profile across properties."),
    "cluster_position_proxy":      ("Chemical Space Cluster Position",
                                    "Normalised percentile rank — position within the approved drug property distribution."),
    "drug_likeness_percentile":    ("Drug-Likeness Percentile Rank (vs FDA Drugs)",
                                    "Percentile position vs FDA approved drug property distributions."),
    "feature_dist_rank":           ("Property Feature Distribution Rank",
                                    "Scaled percentile rank out of 10 — how the compound ranks across the approved drug space."),
    "nearest_neighbor_dist":       ("Nearest Approved Drug Distance",
                                    "Inverse of percentile rank — lower = more similar to approved drugs."),
    "approved_drug_overlap":       ("Approved Drug Property Space Overlap",
                                    "1 if compound falls within FDA-approved drug MW, LogP, TPSA ranges."),
    "clinical_candidate_similarity": ("Clinical Development Candidate Similarity",
                                      "1 if compound fits relaxed criteria matching Phase II clinical candidates."),
    "natural_product_similarity":  ("Natural Product Structural Similarity",
                                    "NP Score normalised to 0–1. Measures structural resemblance to bioactive natural products."),
}


def feat_label(key: str) -> str:
    """Human-readable label for an advanced feature key."""
    entry = FEATURE_LABELS.get(key)
    if entry:
        return entry[0]
    # fallback
    return key.replace("_", " ").replace("idx", "Index").replace("proxy", "Proxy").title()


def feat_tip(key: str) -> str | None:
    """Tooltip for an advanced feature key."""
    entry = FEATURE_LABELS.get(key)
    return entry[1] if entry else None


def feat_label_tip(key: str) -> tuple:
    """Return (label, tooltip) tuple for advanced features."""
    return feat_label(key), feat_tip(key)
